services:
  mosquitto:
    build: ./mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt-net

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      # sobrescreve só o que muda no docker
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    networks:
      - mqtt-net
    depends_on:
      - mosquitto

networks:
  mqtt-net:
    driver: bridge
